<?php

namespace Tests\Feature;

use App\Models\Category;
use App\Models\Post;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

use function route;

class PostControllerTest extends TestCase
{
    // 테스트 간 DB 상태가 서로 영향을 주지 않도록 테스트 DB를 초기화할 수 있다.
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed();
    }

    public function test_게시물_목록(): void
    {
        $user = User::factory()->create();

        Post::factory()
            ->count(3)
            ->for($user)
            ->create();

        $response = $this
            ->actingAs($user)
            ->get(route('posts.index'));

        $response
            ->assertOk()
            ->assertViewIs('posts.index')
            ->assertViewHas('posts');
    }

    public function test_posts_검색()
    {
        $user = User::factory()->create();

        $matchedPost = Post::factory()
            ->for($user)
            ->create([
                'title' => 'Laravel PHPUnit Testing',
                'content' => 'Testing Laravel application',
            ]);

        Post::factory()
            ->create([
                'title' => 'PHP Tutorial',
                'content' => 'Basic PHP',
            ]);

        $response = $this
            ->actingAs($user)
            ->get(route('posts.index', [
                'search' => 'PHPUnit',
            ]));

        $response
            ->assertOk()
            ->assertViewHas('posts', function ($posts) use ($matchedPost): bool {
                return $posts->contains('id', $matchedPost->id);
            });
    }

    public function test_user_can_view_create_post_form()
    {
        $user = User::factory()->create();

        $category = Category::query()->where('is_active', true)->inRandomOrder()->first();

        $response = $this
            ->actingAs($user)
            ->get(route('posts.create'));

        $response
            ->assertOk()
            ->assertViewIs('posts.create')
            ->assertViewHas('categories', function ($categories) use ($category): bool {
                return $categories->contains('id', $category->id);
            });
    }

    public function test_example(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
}
